### PR TITLE
TSM-536: Maintenance: Change relative path to absolute for default.services.yml in site.settings.php

### PR DESCRIPTION
**Pull request by isa-wtag**
**Jira :** https://wearewondrous.atlassian.net/browse/TSM-536

### Background

>   When DRD gets site info from remote site, it also gets all directories to  the service yml file's. 
>   
>   In site.settings.php file psh-toolbelt uses the relative path(../services/default.services.yml) for default.services.yml to the module directory.
>   
>   Upon receiving the info from remote site DRD module tries to make relative path from the web root directory to those service yml files directories. 
>   
>   Since ../services/default/services.yml file is a relative path symfony file system throws error as it expects path to be absolute.

### Goal

- Make path to default.services.yml absolute in site.settings.php

### Acceptance

- Psh-toolbelt still works the same way.

### Test

- Tested if https://github.com/wearewondrous/psh-toolbelt/tree/TSM-536-Maintenance-Absolute-Path-For-default.services.yml is working on already opened https://github.com/wearewondrous/babygalerie-backend/pull/13 with this commit -> https://github.com/wearewondrous/babygalerie-backend/pull/13/commits/c382049f6d300145c47a79c8d143c0d185f70af0. ( Check Branch hash and to ensure we're using the right version of `psh-toolbelt`) 
- ran backup in pr env 
```
web@bfxbqq655tzes-pr-13-7gt46na--ksb_babygalerie:~$ vendor/bin/psh-toolbelt backup:branch --force
 [Exec] Running drush sql:dump | gzip > /app/tmp/babygalerie-bfxbqq655tzes--pr-13--2021-10-28T08:35:10+02:00--dump.sql.gz
 [Exec] Done in 1.147s
 [Exec] Running tar --exclude=.htaccess --exclude=js --exclude=css --exclude=styles --exclude=translations --exclude=languages --exclude=config -c web/sites/default/files/ | gzip > /app/tmp/babygalerie-bfxbqq655tzes--pr-13--2021-10-28T08:35:10+02:00--files-public.tar.gz
 [Exec] Done in 02:10
 [Exec] Running tar --exclude=.htaccess --exclude=js --exclude=css --exclude=styles --exclude=translations --exclude=languages --exclude=config -c private/ | gzip > /app/tmp/babygalerie-bfxbqq655tzes--pr-13--2021-10-28T08:35:10+02:00--files-private.tar.gz
 [Exec] Done in 0.006s
```

**PR running using this change :** https://www.pr-2-tcs3n7y-zt5dpqoo27gdc.eu-4.platformsh.site/

### CODE REVIEW

**Review by luxflux — APPROVED** [review]
Looks good to me, but let's get a review from @Wickeey and @yobottehg on this. Not sure if the relative path was required for some reason?

**Review by zar-wtag — APPROVED** [review]
Looks good to me.

**Review by the-wtag — APPROVED** [review]

**Review by bia-wtag — APPROVED** [review]
LGTM

**Comment by isa-wtag** [comment]
> Looks good to me, but let's get a review from @Wickeey and @yobottehg on this. Not sure if the relative path was required for some reason?

Sure we will put this one for their review once our internal review is done.
This should be okay as this file is being accessed from the current directory

**Review by adi-wtag — APPROVED** [review]

**Review by Wickeey — APPROVED** [review]

**Comment by Wickeey** [comment]
if it works i see no problem with changing the path

**Pull request merged**
